# MangoParty Configuration

# Party Settings
party:
  # Maximum party size
  max-size: 8
  # Invite timeout in seconds
  invite-timeout: 60
  # Auto-disband empty parties
  auto-disband: true

# Match Settings
match:
  # Countdown duration in seconds
  countdown-duration: 5
  # Minimum players required to start a match
  min-players: 2
  # Maximum match duration in minutes (0 = unlimited)
  max-duration: 30

# Arena Settings
arena:
  # Auto-regenerate arenas after matches
  auto-regenerate: true
  # Delay before regeneration in seconds
  regeneration-delay: 5

# Scoreboard Settings
scoreboard:
  title: "&#FFD700&lMangoParty"
  lines:
    - ""
    - "&#FF6B6BArena: &#FFFFFF{arena}"
    - "&#4ECDC4Kit: &#FFFFFF{kit}"
    - "&#45B7D1Mode: &#FFFFFF{match_type}"
    - ""
    - "&#FFE66DStatus: {status}"
    - "&#FF6B6BState: {state}"
    - ""
    - "&#4ECDC4Players Alive: &#FFFFFF{players_alive}/{players_total}"
    - "&#96CEB4Spectators: &#FFFFFF{spectators}"
    - ""
    - "&#FFEAA7Your Stats:"
    - "  &#FF7675Kills: &#FFFFFF{kills}"
    - "  &#74B9FFDeaths: &#FFFFFF{deaths}"
    - ""
    - "&#DDA0DDTeam Info:"
    - "  &#FF6B6BYour Team: &#FFFFFF{your_team_alive}/{your_team_total}"
    - "  &#4ECDC4Enemy Team: &#FFFFFF{opponent_team_alive}/{opponent_team_total}"
    - ""
    - "&#A29BFETime: &#FFFFFF{time}"
    - ""
    - "&#FFD93Dmangoparty.com"

# Messages
messages:
  prefix: "§6[MangoParty] §r"
  party-created: "§aParty created successfully!"
  party-disbanded: "§cParty has been disbanded!"
  invite-sent: "§aInvite sent to {player}!"
  invite-received: "§a{player} §7invited you to their party!"
  player-joined: "§a{player} §7joined the party!"
  player-left: "§c{player} §7left the party!"
  leadership-transferred: "§a{player} §7is now the party leader!"
  match-starting: "§aMatch starting in {seconds} seconds!"
  match-started: "§aMatch started! Good luck!"
  match-ended: "§cMatch ended!"
